
###### Dataset
    root                    : "./data"
    train_json_path         : "train.json"
    val_json_path           : "val.json"
    test_json_path          : "test.json"
    matrix_json_path        : "matrix.json"
    subset                  : 1.0
    batch_size              : 128
    NUM_WORKERS             : 4

    ### Target threshold
    fire_threshold          : 10


###### Model
    ### Adjacency matrix
    local_var_lag           : 8
    oci_var_lag             : 31
    max_lag                 : 312
    independence_test       : "ParCorr"
    tau_max                 : 186
    pc_alpha                : 0.05
    mask_target             : True

    ### Temporal LSTM
    lstm_layer              : 1
    hidden_dim              : 256

    ### GNN
    gnn_nodes               : 7


###### Training
    epochs                  : 30

    lr                      : 1.0e-5
    min_lr                  : 1.0e-9
    
    optimizer               : "Adam"
    betas                   : [0.9, 0.999]
    eps                     : 1.0e-8
    weight_decay            : 5.0e-6

    lr_scheduler            : "CosineAnnealingLR"
    patience                : 10
    early_stop              : True

    save_model              : True
    save_model_path         : "./checkpoints"
    load_model              : False
    load_model_path         : "./checkpoints/best.pth"
    wandb_log               : True
    wandb_project           : "IDL_Final"
    wandb_run_id            : None
